# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iveCVvSeyK9_o5xlRUv5ZJ5ZfEPk5AzD
"""

# Commented out IPython magic to ensure Python compatibility.
import ipywidgets as widgets
from IPython.display import display
import geometry
import electron_density

def launch_app():
    title = widgets.Label('Electron Density Visualization App', style={'font_weight': 'bold', 'font_size': '20px'})

    # Geometry Layout (already built inside geometry.py)
    geom_label = widgets.Label('Step 1: Define Geometry and Generate fort.45 File')
    geom_section = geometry.layout

    # Upload Section
    upload_label = widgets.Label('Step 2: Upload Waves and Transmissions Files')
    waves_upload = widgets.FileUpload(accept='.txt', multiple=False)
    transmissions_upload = widgets.FileUpload(accept='.txt', multiple=False)

    def save_uploaded_file(uploaded, filename):
        with open(filename, 'wb') as f:
            f.write(list(uploaded.value.values())[0]['content'])

    upload_output = widgets.Output()
    upload_button = widgets.Button(description="Save Uploaded Files", button_style='success')

    def upload_clicked(b):
        with upload_output:
            upload_output.clear_output()
            if waves_upload.value and transmissions_upload.value:
                save_uploaded_file(waves_upload, "waves (2).txt")
                save_uploaded_file(transmissions_upload, "tr_b (2).txt_fixed")
                print("Files saved successfully!")
            else:
                print("Please upload both files.")

    upload_button.on_click(upload_clicked)

    # Run Electron Density
    ed_label = widgets.Label('Step 3: Generate Electron Density Video')
    run_ed_button = widgets.Button(description="Run Simulation", button_style='info')
    run_ed_output = widgets.Output()

    def run_ed_clicked(b):
        with run_ed_output:
            run_ed_output.clear_output()
            try:
#                 %run electron_density.py
                print("Electron density animation created successfully!")
            except Exception as e:
                print(f"Error: {e}")

    run_ed_button.on_click(run_ed_clicked)

    # Final Layout
    app_layout = widgets.VBox([
        title,
        geom_label, geom_section,
        widgets.HBox([waves_upload, transmissions_upload, upload_button]),
        upload_output,
        ed_label, run_ed_button, run_ed_output
    ])

    display(app_layout)

launch_app()